### ISSUE TITLE
Fix gene symbol filter

### ISSUE THREAD

**Issue by tanyasg** [allen-cell-animated/cell-line-catalog#121]
Filtering is broken for multi-edit lines and does not behave as expected for these multi-edit lines. Multi-edits (ex. FBL/NPM1) should not appear in the filter dropdown, instead only the single gene symbols from the second tab in Irina's spreadsheet (see attached; Filter Gene Symbol tab) should appear. A single gene filter (ex. FBL) should retrieve both single edit and multi-edit lines (ex. FBL should retrieve AICS14, 84, 86, and 89). 

Acceptance criteria:

- [x] "Filter by Gene" is changed to "Filter by Gene Symbol"
- [x] Filter by Gene Symbol dropdown contains only genes listed in Irina's spreadsheet (see attached; Filter Gene Symbol tab)
- [x] filtering works for multi-edit lines (each gene symbol filter should retrieve the list of lines in Irina's spreadsheet; (see attached -> Filter Gene Symbol tab)
- [x] gene symbols are in alphabetical order in dropdown
[Cell Catalog corrections and filters.xlsx](https://github.com/allen-cell-animated/cell-line-catalog/files/6503539/Cell.Catalog.corrections.and.filters.xlsx)

**Comment by songziz** [comment]
Do we want to include symbols for cell lines in progress? For example, G3BP?
