### ISSUE TITLE
Fix structure filter

### ISSUE THREAD

**Issue by tanyasg** [allen-cell-animated/cell-line-catalog#122]
Filtering is broken for multi-edit lines and does not behave as expected for these multi-edit lines. Multi-edits (ex. Endoplasmic reticulum/nuclear envelope) should not appear in the filter dropdown, instead only the single structures from the 4th tab in Irina's spreadsheet (see attached; Filter Structure tab) should appear. A single structure filter (ex. endoplasmic reticulum) should retrieve both single edit and multi-edit lines (ex. endoplasmic reticulum should retrieve AICS10, 46, 59).

Acceptance criteria:

- [x] Filter by Gene Structure dropdown contains only structures listed in Irina's spreadsheet (see attached; Filter Structure tab)
- [x] filtering works for multi-edit lines (each structure filter should retrieve the list of lines in Irina's spreadsheet; (see attached -> Filter Structure tab)
- [x] structures are in alphabetical order in dropdown
[Cell Catalog corrections and filters.xlsx](https://github.com/allen-cell-animated/cell-line-catalog/files/6503565/Cell.Catalog.corrections.and.filters.xlsx)

**Comment by songziz** [comment]
There exists inconsistent capitalization of words for (nucleolus) structure that we might want to address

**Comment by songziz** [comment]
microtubules vs Microtubules
